import json, sys

ts = "2026-06-11T10:45:00-07:00"

def w(path, ticker, articles):
    with open(path, "a") as f:
        for art in articles:
            rec = {
                "article_id": art[0],
                "ticker": ticker,
                "run_date": "2026-06-11",
                "analyzed_at": ts,
                "headline": art[1],
                "publisher": art[2],
                "url": art[3],
                "sentiment": art[4],
                "score": art[5],
                "summary": art[6],
                "analysis_error": None
            }
            f.write(json.dumps(rec) + "\n")
    print(f"{ticker} 2026-06-11: {len(articles)} analyzed")

# TSLA
w("data/TSLA/sentiment_log.jsonl", "TSLA", [
("09c6703ac4c611ef1e1d1fa9","SpaceX IPO: Record-breaking deal prices at $135. Trading begins on Friday.","(MarketWatch)","https://www.marketwatch.com/livecoverage/spacex-ipo-stock-price-trading-elon-musk-spcx?mod=mw_FV","neutral",0.0,"SpaceX IPO at $1.77T now exceeds Tesla market cap, shifting investor capital allocation away from TSLA."),
("09fe12d4456c16b6708cae75","Does Elon Musk have too much influence in space?","(CNBC TV)","https://www.youtube.com/shorts/PhH5lkJfUxo","bearish",-0.2,"Governance concerns about Musk's concentrated power raise key-man risk for TSLA investors."),
("17ab783497f8e04fa1ccc1aa","Tesla Stock Needs the SpaceX IPO to Happen Already","(Barrons.com)","https://www.barrons.com/articles/tesla-stock-price-spacex-ipo-selling-949d5661?mod=bar_FV","bullish",0.4,"Tesla stock rose on SpaceX IPO order-book close, removing overhang and letting TSLA trade on its own fundamentals."),
("28f96719f92b3553473a648c","SpaceX raises $75 billion in its IPO","(Axios)","https://finance.yahoo.com/m/ef5cb1bd-bb7a-3c36-8376-d685d8e6fa76/spacex-raises-%2475-billion-in.html","neutral",0.1,"SpaceX $75B IPO makes Musk world's first trillionaire; indirectly positive for TSLA but SpaceX now exceeds Tesla's market cap."),
("2982840973b731c210f34739","Tesla Robotaxi Rollout Faces Fresh Scrutiny","(GuruFocus.com)","https://finance.yahoo.com/markets/stocks/articles/tesla-robotaxi-rollout-faces-fresh-161503980.html","bearish",-0.6,"Tesla Austin robotaxi fleet only 59 vehicles with long waits and booking failures, well below bearish expectations, undermining autonomous revenue narrative."),
("3cbb8663b9e87c4734b4fb31","SpaceX's stock could follow the same path as Tesla - not always trading on fundamentals","(MarketWatch)","https://www.marketwatch.com/story/spacexs-stock-could-follow-the-same-path-as-tesla-not-always-trading-on-fundamentals-41e1ffa2?mod=mw_FV","neutral",-0.1,"Comparison highlights Tesla's faith-based investing dynamic and valuation premium driven by narrative rather than fundamentals."),
("54a32db0d907441b4de59a67","Beyond Elon Musk: A closer look at SpaceX's C-suite","(Yahoo Finance Video)","https://finance.yahoo.com/video/beyond-elon-musk-a-closer-look-at-spacexs-c-suite-151330496.html","neutral",0.0,"SpaceX management profile with no direct Tesla implications."),
("55193a8fd4af7332e2d90327","The Number That Complicates The Tesla Stock Story","(Trefis)","https://finance.yahoo.com/m/e1ecb0dd-bb92-3569-a850-1411d68c93da/the-number-that-complicates.html","bearish",-0.5,"Tesla revenue growth decelerated to 2.3% against 12.3x price-to-sales multiple, creating de-rating risk as structural slowdown becomes harder to justify."),
("5b07ef0f98e582c8eced849a","SpaceX is officially worth more than Tesla, Meta and Walmart","(MarketWatch)","https://www.marketwatch.com/livecoverage/spacex-ipo-stock-price-trading-elon-musk-spcx/card/spacex-is-officially-worth-more-than-tesla-meta-and-walmart-V556Z2lSCEZjnPE5qm80?mod=mw_FV","bearish",-0.3,"SpaceX $1.77T now exceeds Tesla $1.43T, potentially drawing capital and investor attention away from TSLA."),
("5fb58ae2c2c255f718b7cf1d","xAI Alumni Launch River AI as Agent Race Heats Up","(GuruFocus.com)","https://finance.yahoo.com/sectors/technology/articles/xai-alumni-launch-river-ai-170322683.html","neutral",-0.1,"Former xAI and Tesla talent departing signals minor talent drain headwind for Tesla's AI ambitions."),
("6581c5eaa609a89f2640d32f","Why Elon Musk is the 'king of big ideas'","(Yahoo Finance Video)","https://finance.yahoo.com/video/why-elon-musk-is-the-king-of-big-ideas-200023430.html","bullish",0.2,"Positive Musk brand narrative reinforces cult-of-personality investing thesis supporting TSLA premium valuation."),
("68d9bb9c7dff5f2a98898b28","Brace for SpaceX's stock to show 'extreme' volatility, a bullish analyst warns","(MarketWatch)","https://www.marketwatch.com/story/brace-for-spacexs-stock-to-show-extreme-volatility-a-bullish-analyst-warns-589ea226?mod=mw_FV","neutral",0.0,"SpaceX volatility warning not directly relevant to Tesla near-term price action."),
("6d02a0dedbd8fb1cef04d787","Investors Awoke to 'A Dip Buyer's Dream' Today. But Next Week's Fed Meeting Looms Large","(Investopedia)","https://finance.yahoo.com/m/1594df2d-c43c-364a-9e20-4b466f77912a/investors-awoke-to-%27a-dip.html","bullish",0.3,"Tesla was one of only two Mag-7 stocks posting gains during broad tech selloff, demonstrating relative strength attracting rotation buyers."),
("7204a5180da9437648e50acc","Elon Musk Is (Still) a Trillionaire","(Barrons.com)","https://www.barrons.com/livecoverage/spacex-ipo-stock-price-spcx-elon-musk/card/elon-musk-is-still-a-trillionaire-171nNxT70duVAD4yFJT5?mod=bar_FV","neutral",0.1,"Musk $1.1T combined net worth reinforces his financial alignment with TSLA shareholders."),
("749ead95c34d818d8f50d881","Long-term SpaceX investors shouldn't be 'optimistic,' expert says","(Yahoo Finance Video)","https://finance.yahoo.com/video/long-term-spacex-investors-shouldnt-be-optimistic-expert-says-165640160.html","neutral",-0.1,"Expert faith-based investing skepticism about SpaceX applies equally to Tesla's narrative-driven valuation."),
("80ed361c67899187cf6792a8","SpaceX IPO makes Elon Musk the world's first trillionaire","(Reuters)","https://finance.yahoo.com/markets/stocks/articles/spacex-ipo-makes-elon-musk-220634604.html","neutral",0.0,"Musk trillionaire status raises his profile but also intensifies scrutiny of divisive political actions, a mixed signal for Tesla brand."),
("9cb9826fbf3db405069b349a","SpaceX's $1.8 Trillion IPO Could Reset Private Markets","(GuruFocus.com)","https://finance.yahoo.com/markets/stocks/articles/spacexs-1-8-trillion-ipo-183711653.html","neutral",-0.1,"SpaceX IPO at $1.77T eclipses Tesla valuation, potentially framing TSLA as less attractive in Musk's portfolio."),
("a51170dfa7058da608646b0f","SpaceX to make historic IPO that could make Musk a trillionaire","(AFP)","https://finance.yahoo.com/markets/stocks/articles/spacex-cusp-record-ipo-could-013526589.html","neutral",0.0,"SpaceX historic IPO dominates news cycle and may temporarily shift capital away from TSLA."),
("b128422e0e5eecd4e969fa91","Rivian's Big Day Out, Wall Street's Big Thumbs Down","(Trefis)","https://finance.yahoo.com/m/8a485c10-8f98-3b03-ae2d-5416e1c8b5b5/rivian%27s-big-day-out%2C-wall.html","bearish",-0.2,"EV sector broadly sold off with Tesla down 3.8%, reflecting sector-wide pressure on electric vehicle growth narratives."),
("b8a8b5060f08b8652c9907a0","SpaceX Tesla Merger Odds Are Rising","(Barrons.com)","https://www.barrons.com/livecoverage/spacex-ipo-stock-price-spcx-elon-musk/card/spacex-tesla-merger-odds-are-rising-uu5Mv00ZsO2b2tUkYYaI?mod=bar_FV","bullish",0.5,"Rising SpaceX-Tesla merger speculation could unlock significant value for TSLA shareholders if Musk's empire consolidates under one public entity."),
("c36a00c302299ea34a2e0032","SpaceXs prices historic IPO at $135/share in largest ever new listing","(Investing.com)","https://finance.yahoo.com/markets/stocks/articles/spacex-historic-ipo-catapults-past-201231064.html","neutral",-0.1,"SpaceX now ranked seventh among US-listed companies at $1.77T, displacing Tesla from its comparative standing in Musk's portfolio."),
("cb5e1f9f83ae96a342aace77","SpaceX IPO Draws More Than $100 Billion in Retail Orders","(Bloomberg)","https://finance.yahoo.com/markets/stocks/articles/spacex-ipo-draws-more-70-124106841.html","neutral",0.0,"Massive retail demand for SpaceX could temporarily draw retail flows previously supporting TSLA."),
("d3ca83dbf73dfe6ee30b305d","Gwynne Shotwell is the 'unsung hero' of SpaceX as its blockbuster IPO launches","(MarketWatch)","https://www.marketwatch.com/story/gwynne-shotwell-is-the-unsung-hero-of-spacex-as-its-blockbuster-ipo-launches-05f57fac?mod=mw_FV","neutral",0.0,"SpaceX operational leadership profile; not directly relevant to Tesla near-term outlook."),
("e5287439e828b983faed98a4","Big Tech stocks mostly fall, with Alphabet and Microsoft posting sharp losses","(MarketWatch)","https://www.marketwatch.com/livecoverage/stock-market-today-dow-jones-s-p-500-nasdaq-spacex-ipo-us-iran-exchange-strikes/card/big-tech-stocks-mostly-fall-with-alphabet-and-microsoft-posting-sharp-losses-qkoQZdB0gHmkbczEUcvm?mod=mw_FV","bullish",0.3,"Tesla gained when most Mag-7 stocks fell sharply, signaling relative strength and potential investor rotation into TSLA."),
("e7c48f2f049a3e798cf1fe8d","NIO Stock Climbs  Onvo Launches Refreshed L60 At Lower Price To Challenge Tesla Model Y","(Stocktwits)","https://finance.yahoo.com/m/059eecb0-248b-3f2c-9f5d-c30be4424631/nio-stock-climbs-%E2%80%94-onvo.html","bearish",-0.4,"NIO Onvo refreshed L60 SUV priced 27% below Tesla Model Y in China, intensifying competitive pressure on Tesla's key market."),
("f9459d6a88680f8d0adb9e1e","SpaceX Prices IPO at $135, Raising Up to $86 Billion","(Barrons.com)","https://www.barrons.com/livecoverage/spacex-ipo-stock-price-spcx-elon-musk?mod=bar_FV","neutral",0.0,"SpaceX priced at $1.8T with AI computing orbit strategy; neutral for TSLA as companies serve different market segments."),
])

# META
w("data/META/sentiment_log.jsonl", "META", [
("06ca255a5e5a6d19e5627402","SpaceX takes unconventional route to pricing its stock ahead of IPO","(Yahoo Finance Video)","https://finance.yahoo.com/video/spacex-takes-unconventional-route-to-pricing-its-stock-ahead-of-ipo-202708577.html","neutral",0.0,"SpaceX IPO pricing mechanics article; not directly relevant to Meta fundamentals."),
("16febbfabe78d9506a5b0d57","The Best Mid-Cap ETFs to Buy","(Kiplinger)","https://finance.yahoo.com/m/b6ecb4ae-8f23-3e2e-9472-ee5a0849fdbc/the-best-mid-cap-etfs-to-buy.html","neutral",0.0,"General ETF article mentioning Meta as a Mag-7 component; no specific Meta signal."),
("1ac32f8180d69b1dab4e2817","Meta Expands AI Partnership With Reliance","(GuruFocus.com)","https://finance.yahoo.com/sectors/technology/articles/meta-expands-ai-partnership-reliance-194349936.html","bullish",0.4,"Meta-Reliance 168MW India data center deal expands AI infrastructure and deepens strategic partnership in the world's fastest-growing large market."),
("1bb8be0d70cb02520ff57d4c","Google and Meta denied new trial in youth social media addiction case","(Reuters)","https://finance.yahoo.com/news/google-meta-denied-trial-youth-163334154.html","bearish",-0.4,"Court denied new trial in $6M youth addiction case, sustaining liability verdict and signaling Section 230 may not protect Meta's design choices from future claims."),
("1f5053b16be105fd0fd494c9","Meta signs AI data centre agreement with Reliance in India","(Investment Monitor)","https://finance.yahoo.com/m/02e8f7ac-cbe8-37da-9778-ee206a508410/meta-signs-ai-data-centre.html","bullish",0.4,"Meta's first AI-enabled Indian data center with Reliance deepens its infrastructure presence in a key growth market with renewable energy integration."),
("1fbe2d540b8783baf180815c","SpaceX's market meteoric debut by the numbers","(Reuters Videos)","https://finance.yahoo.com/video/spacexs-market-meteoric-debut-numbers-150711634.html","neutral",0.0,"SpaceX IPO metrics overview; minimal direct relevance to Meta fundamentals."),
("4df9b5a142b99386aada55ee","SpaceX locks in IPO price of $135, making it largest stock debut ever","(NBC News)","https://finance.yahoo.com/m/05bf16dc-7b8b-3123-b983-4b613fb4a508/spacex-locks-in-ipo-price-of.html","neutral",-0.1,"SpaceX IPO confirms it is now valued above Meta at $1.77T vs Meta $1.45T, implying META may attract less capital in the near term."),
("5b07ef0f98e582c8eced849a","SpaceX is officially worth more than Tesla, Meta and Walmart","(MarketWatch)","https://www.marketwatch.com/livecoverage/spacex-ipo-stock-price-trading-elon-musk-spcx/card/spacex-is-officially-worth-more-than-tesla-meta-and-walmart-V556Z2lSCEZjnPE5qm80?mod=mw_FV","neutral",-0.1,"SpaceX surpassing Meta's market cap could draw Mag-7 comparison capital away from META."),
("5c8fd1fe7cb3bd0c3571bb4f","Meta and Google denied new trial in youth addiction lawsuit","(Quartz)","https://finance.yahoo.com/m/9e12ce13-f5ee-31ab-89f4-cda19b27a2fa/meta-and-google-denied-new.html","bearish",-0.4,"Second source confirming Meta denied new trial in youth addiction case, expanding legal exposure precedent for future design-based litigation."),
("62f38dc026e1e71e5cc00eeb","Meta navigates AI investment cycle as Street weighs costs against returns","(Proactive)","https://finance.yahoo.com/m/86bd677d-7be6-3c9a-b110-941ba46e1d66/meta-navigates-ai-investment.html","bearish",-0.3,"BofA analysis highlights Meta stock has underperformed 24% since capex guidance increase, with AI ROI timeline unclear despite advertising improvements."),
("62fdcdd411266c15972d0f45","There's a New Stock to Play the AI Power Boom, and It's Down Today","(Barrons.com)","https://www.barrons.com/articles/erock-stock-ipo-price-ai-datacenter-power-2aeaf3ef?mod=bar_FV","neutral",0.0,"AI power sector article; minimal direct Meta relevance."),
("6d02a0dedbd8fb1cef04d787","Investors Awoke to 'A Dip Buyer's Dream' Today. But Next Week's Fed Meeting Looms Large","(Investopedia)","https://finance.yahoo.com/m/1594df2d-c43c-364a-9e20-4b466f77912a/investors-awoke-to-%27a-dip.html","bearish",-0.2,"Meta was one of the Mag-7 stocks that did not participate in the recovery day, signaling relative weakness."),
("7462d52ccfa9141f8a1b8f99","Is Amazon's $225 Billion AI Chip Bet Too Big To Fail?","(Trefis)","https://finance.yahoo.com/m/5f707792-d7f8-3d23-80c2-9ef86d5fc20c/is-amazon%27s-%24225-billion-ai.html","neutral",0.0,"Amazon AI chip strategy article; not directly relevant to Meta."),
("881fdd87869124be7f4eba24","Is Meta Spending Too Much On AI?","(Trefis)","https://finance.yahoo.com/m/ea68cc05-9cd1-3780-96b4-9941f89bddc6/is-meta-spending-too-much-on.html","bearish",-0.4,"Meta 2026 capex guidance of $125-145B consumes 62% of operating cash flow, with management admitting they consistently underestimate compute needs."),
("99bf8657146da61d8ac890a9","Meta and X Face Canada Youth Ban Risk","(GuruFocus.com)","https://finance.yahoo.com/sectors/technology/articles/meta-x-face-canada-youth-145719961.html","bearish",-0.3,"Canada proposed youth social media ban for under-16 users with 3% global revenue penalties, adding regulatory pressure on top of Australia-style global trend."),
("9e8b195d8ba8746cc84df1db","Meta Announces PPA With RWE for 298-MW Texas Solar Power Project","(POWER Magazine)","https://finance.yahoo.com/m/c72c6bd3-03a8-39f9-9c93-c40b3f256654/meta-announces-ppa-with-rwe.html","bullish",0.2,"Meta 298MW renewable energy PPA advances clean energy commitments and demonstrates responsible AI infrastructure scaling."),
("a51170dfa7058da608646b0f","SpaceX to make historic IPO that could make Musk a trillionaire","(AFP)","https://finance.yahoo.com/markets/stocks/articles/spacex-cusp-record-ipo-could-013526589.html","neutral",0.0,"SpaceX IPO noted as exceeding Meta market cap; broad market event with minor Meta implications."),
("a6c7eebbcdeb101f078b76b0","Trump says he thinks AI companies will agree to 'giving back' to the public","(Reuters)","https://finance.yahoo.com/sectors/technology/articles/trump-says-thinks-ai-companies-163038299.html","bearish",-0.3,"Trump's suggestion AI companies give government equity stakes introduces potential forced dilution risk for Meta and other major AI firms."),
("a9c58615418e91a4daa848a8","Amazon Taps $17.5 Billion Loan as AI Spending Race Intensifies","(GuruFocus.com)","https://finance.yahoo.com/markets/stocks/articles/amazon-taps-17-5-billion-183906224.html","neutral",-0.1,"AI capex race context article mentioning Meta's record bond offering; reinforces elevated spending environment for META."),
("af6d5c789761009d58feedc2","Canada Unveils Youth Social Media Ban With 3% Revenue Penalty Risk","(GuruFocus.com)","https://finance.yahoo.com/sectors/technology/articles/canada-unveils-youth-social-media-174722464.html","bearish",-0.3,"Canada bill would temporarily ban under-16 users from Meta platforms pending regulator setup, representing material near-term revenue and compliance risk."),
("b1c20c4e29ccbd3c47866185","Oracle shares slide as hefty AI spending, debt plans spook investors","(Reuters)","https://finance.yahoo.com/markets/stocks/articles/oracle-shares-slide-hefty-ai-152535544.html","neutral",-0.1,"Oracle's capex shock selloff raises investor anxiety about AI spending ROI broadly, a sentiment risk that also applies to Meta's $125-145B capex plan."),
("ba489e40251b170d8ea5e454","AI stocks: MANGOS ascends, replacing FAANG position","(Yahoo Finance Video)","https://finance.yahoo.com/video/ai-stocks-mangos-ascends-replacing-faang-position-200651767.html","bullish",0.2,"Meta remains in the new MANGOS acronym replacing FAANG, confirming its position as a core AI holding for institutional investors."),
("c36a00c302299ea34a2e0032","SpaceXs prices historic IPO at $135/share in largest ever new listing","(Investing.com)","https://finance.yahoo.com/markets/stocks/articles/spacex-historic-ipo-catapults-past-201231064.html","neutral",-0.1,"SpaceX valuation confirms it exceeds Meta's market cap, a comparative headwind for META in Mag-7 investment narratives."),
("c4ec17101160e5412daec0b8","These 2 things are key for Meta stock re-rating: BofA","(Investing.com)","https://finance.yahoo.com/markets/stocks/articles/2-things-key-meta-stock-150159674.html","bullish",0.4,"BofA reiterates Buy with $835 target, citing frontier AI model development and scaled adoption of new AI products as re-rating catalysts within 9 months."),
("e5287439e828b983faed98a4","Big Tech stocks mostly fall, with Alphabet and Microsoft posting sharp losses","(MarketWatch)","https://www.marketwatch.com/livecoverage/stock-market-today-dow-jones-s-p-500-nasdaq-spacex-ipo-us-iran-exchange-strikes/card/big-tech-stocks-mostly-fall-with-alphabet-and-microsoft-posting-sharp-losses-qkoQZdB0gHmkbczEUcvm?mod=mw_FV","bearish",-0.2,"Meta was one of the Mag-7 stocks that fell on the recovery day while Tesla and Nvidia gained, indicating underperformance vs peers."),
("e990a7f47652d3ddae28c954","Jeremy Strong becomes Mark Zuckerberg in 'Social Network' sequel","(Yahoo Finance Video)","https://finance.yahoo.com/video/jeremy-strong-becomes-mark-zuckerberg-in-social-network-sequel-202255265.html","neutral",0.0,"Social Network sequel publicity keeps Meta in the cultural spotlight but is unlikely to affect near-term financials."),
])

# MU
w("data/MU/sentiment_log.jsonl", "MU", [
("24f0b57e6c6fb2433d376413","The Spill: Is Broadcom (AVGO) the Other AI Trade?","(IPO-Edge.com)","https://finance.yahoo.com/markets/stocks/articles/spill-broadcom-avgo-other-ai-214117164.html","bullish",0.3,"Broadcom AI semiconductor revenue up 143% YoY highlights strong AI chip sector demand that benefits Micron's memory products."),
("30a2bc373d40866a98ec24cf","Wall St edges up as chips rebound, Middle East in focus","(Reuters)","https://finance.yahoo.com/markets/stocks/articles/wall-st-edges-chips-rebound-161530914.html","bullish",0.5,"PHLX Semiconductor index surged 7.9% in its biggest one-day gain since April 2025, with chipmakers leading the S&P 500 recovery."),
("4af364322603245b3e7e2867","Micron Advances New York Chip Project","(GuruFocus.com)","https://finance.yahoo.com/sectors/technology/articles/micron-advances-york-chip-project-184657679.html","bullish",0.4,"Micron named Bechtel as construction partner for New York fab, expected to become largest US semiconductor facility, securing long-term domestic supply capacity."),
("521525be9e57f47ad1011c16","Micron's stock rebounds after 'healthy' reset, and analysts see blue skies ahead","(MarketWatch)","https://www.marketwatch.com/story/microns-stock-rebounds-after-healthy-reset-and-analysts-see-blue-skies-ahead-624a53ef?mod=mw_FV","bullish",0.5,"Morgan Stanley calls Micron's 15% pullback from peak a healthy reset, with analysts pointing to valuation expansion potential ahead of strong memory cycle."),
("5b07ef0f98e582c8eced849a","SpaceX is officially worth more than Tesla, Meta and Walmart","(MarketWatch)","https://www.marketwatch.com/livecoverage/spacex-ipo-stock-price-trading-elon-musk-spcx/card/spacex-is-officially-worth-more-than-tesla-meta-and-walmart-V556Z2lSCEZjnPE5qm80?mod=mw_FV","bullish",0.3,"Article notes Micron recently crossed $1T market cap milestone alongside SpaceX comparison; validates Micron's position in the trillion-dollar club."),
("68335a5d7f3b35105bb02361","Micron Moves Ahead With Massive New York Fab","(GuruFocus.com)","https://finance.yahoo.com/sectors/technology/articles/micron-moves-ahead-massive-york-184547779.html","bullish",0.4,"Micron's Clay, NY fab with Bechtel partnership expands US manufacturing footprint at a time of surging AI-driven memory demand."),
("6a23360d0e0414e460733ad7","How Super Micro, Lam Research, and More Stocks Explain Today's Market","(Barrons.com)","https://www.barrons.com/articles/stock-market-movers-today-super-micro-lam-research-e4f7a2ee?mod=bar_FV","bullish",0.3,"Chipmakers including Micron rebounded strongly as investors loaded back up on semiconductor shares after a two-session selloff."),
("6b654ec135731dfaf606db03","The AI buildout is still intact  what to buy this week","( TheStreet)","https://finance.yahoo.com/m/926d77a5-285d-3ae6-867c-f89b28968b91/the-ai-buildout-is-still.html","bullish",0.5,"Analyst Patrick Moorhead explicitly names Micron as one of the best-positioned AI buildout plays to buy, affirming AI demand is intact."),
("6bb18de4c1f13372adbd644c","Micron, Intel drag the tech sector into a new bearish phase. Will the correction last this time?","(MarketWatch)","https://www.marketwatch.com/story/micron-intel-drag-the-tech-sector-into-a-new-bearish-phase-will-the-correction-last-this-time-9ba4f3f5?mod=mw_FV","bearish",-0.3,"Micron named as leading driver of tech sector correction entering official bearish phase, though analysts note weakness is more technical than fundamental."),
("8045b0aad5cf5948dfc75232","This Semiconductor Stock Has More Than Tripled This Year  But Wolfe Research Sees Another 36% Upside","(Stocktwits)","https://finance.yahoo.com/m/f1359cab-f013-3e92-9c88-2485f3875d68/this-semiconductor-stock-has.html","bullish",0.8,"Wolfe Research raised Micron target to $1,250 from $550 citing 45% Q3 memory price increase; Daiwa raised to $1,600 from $700 on HBM pricing strength."),
("98dfdc2554435faa23cc3a79","Nasdaq, S&P Drop 1%, Dow Sinks 600 Points as Trump Iran Threat Sparks Market Panic","(GuruFocus.com)","https://finance.yahoo.com/markets/articles/nasdaq-p-drop-1-dow-193300784.html","bearish",-0.3,"Micron fell for fourth time in five sessions amid broad semiconductor selloff driven by Iran escalation fears and portfolio rotation ahead of SpaceX IPO."),
("ce6530c861888ae2bd8d02a0","Seagate Stock's High-Density Gamble","(Trefis)","https://finance.yahoo.com/m/ea2debbe-317d-3dd0-9e05-0e35d283f1c5/seagate-stock%27s-high-density.html","bullish",0.2,"Seagate structural AI data growth narrative underscores the same AI-driven storage demand trend that benefits Micron's memory products."),
("d55a9b923b4fccb88ca4de31","Intel Stock And The Hyperscaler's Tell","(Trefis)","https://finance.yahoo.com/m/ebb1097a-df9f-3772-afcc-d6cd3e2db309/intel-stock-and-the.html","neutral",0.1,"Intel's hyperscaler AI chip wins context; positive for AI silicon sector broadly including Micron's HBM memory."),
("e63de683e3771a76b504770b","When Will the Nasdaq and Semiconductor Selloff End? The Charts Offer Clues.","(Barrons.com)","https://www.barrons.com/articles/nasdaq-semiconductor-stocks-selloff-technical-analysis-b189b272?mod=bar_FV","bearish",-0.2,"Technical analysis notes semiconductor sector selloff may not fully exhaust until capitulation signals appear, suggesting near-term Micron price pressure."),
("f95023b216c0a76badf50667","Micron Jumps on Wolfe Target Raise","(GuruFocus.com)","https://finance.yahoo.com/markets/stocks/articles/micron-jumps-wolfe-target-raise-145635346.html","bullish",0.7,"Wolfe Research raised Micron to $1,250 citing DRAM/NAND demand growing faster than supply with pricing strength through 2026-2027 and HBM margin improvement ahead."),
])

print("BATCH partial done")
