#!/usr/bin/env python3
"""Append 2026-06-17 sentiment analysis records to sentiment_log.jsonl files."""
import json
import os

TS = "2026-06-17T08:15:00-07:00"
BASE = "/Users/krutik/technical/finvizCrawl/data"


def append_records(ticker, records):
    path = os.path.join(BASE, ticker, "sentiment_log.jsonl")
    with open(path, "a") as f:
        for r in records:
            f.write(json.dumps(r) + "\n")
    print(f"{ticker} 2026-06-17: {len(records)} analyzed")


# ── TSLA ──────────────────────────────────────────────────────────────────────
tsla = [
    dict(article_id="021a6545b5a4b8c275061175", ticker="TSLA", run_date="2026-06-17", analyzed_at=TS,
         headline="Startup Backed by Ex-Google CEO Debuts Robot, LG Partnership",
         publisher="(Bloomberg)",
         url="https://finance.yahoo.com/technology/ai/articles/startup-backed-ex-google-ceo-030704320.html",
         sentiment="neutral", score=0.1,
         summary="Article highlights the growing humanoid robot investment landscape where Tesla competes alongside other AI robotics startups.",
         analysis_error=None),
    dict(article_id="14181efc791a14401110c4c6", ticker="TSLA", run_date="2026-06-17", analyzed_at=TS,
         headline="Apple Investors Are Tired of AI Promises, Want Tangible Progress",
         publisher="(Bloomberg)",
         url="https://finance.yahoo.com/technology/ai/articles/apple-investors-tired-ai-promises-112159204.html",
         sentiment="neutral", score=0.0,
         summary="Article about Apple AI struggles has minimal direct impact on Tesla EV and robotics outlook.",
         analysis_error=None),
    dict(article_id="22eb2ee6f67861127ae56f2f", ticker="TSLA", run_date="2026-06-17", analyzed_at=TS,
         headline="SpaceX's near $3 trillion rally comes with one big catch: Chart of the Day",
         publisher="(Yahoo Finance)",
         url="https://finance.yahoo.com/markets/article/spacexs-near-3-trillion-rally-comes-with-one-big-catch-chart-of-the-day-122114608.html",
         sentiment="bearish", score=-0.3,
         summary="SpaceX rapid market cap surge past Tesla signals investor capital rotation away from TSLA toward SpaceX as the preferred Elon Musk vehicle.",
         analysis_error=None),
    dict(article_id="4d00c4a6cb515f7eaac0d21a", ticker="TSLA", run_date="2026-06-17", analyzed_at=TS,
         headline="Uber and Lucid pick Houston as next robotaxi market as battle with Waymo, Tesla heats up",
         publisher="(Yahoo Finance)",
         url="https://finance.yahoo.com/markets/stocks/article/uber-and-lucid-pick-houston-as-next-robotaxi-market-as-battle-with-waymo-tesla-heats-up-111946695.html",
         sentiment="bearish", score=-0.2,
         summary="Expanding Uber-Lucid robotaxi network adds competitive pressure to Tesla autonomous vehicle commercialization efforts.",
         analysis_error=None),
    dict(article_id="66c149ea330247c41b4832e1", ticker="TSLA", run_date="2026-06-17", analyzed_at=TS,
         headline="Xiaomi Auto veteran says Tesla's EV edge starts on factory floor",
         publisher="(DigiTimes)",
         url="https://www.digitimes.com/news/a20260617PD202/xiaomi-automotive-vehicle-manufacturing-supply-chain.html",
         sentiment="bullish", score=0.3,
         summary="Industry veteran acknowledgment of Tesla manufacturing superiority validates its competitive moat on the EV factory floor.",
         analysis_error=None),
    dict(article_id="75e4293ff4a55a96ebdcc90d", ticker="TSLA", run_date="2026-06-17", analyzed_at=TS,
         headline="Cathie Wood Swaps Tesla for SpaceX in $529M Elon Musk Pivot",
         publisher="(BeInCrypto)",
         url="https://finance.yahoo.com/m/f26740e4-c8a0-3619-95b4-8cc9586dca0c/cathie-wood-swaps-tesla-for.html",
         sentiment="bearish", score=-0.5,
         summary="Cathie Wood high-profile $529M rotation from Tesla to SpaceX signals fading institutional conviction in TSLA amid Chinese EV competition and margin pressure.",
         analysis_error=None),
    dict(article_id="9fd0d27b111c3681a6dcf14f", ticker="TSLA", run_date="2026-06-17", analyzed_at=TS,
         headline="What History Suggest About SpaceX's Explosive IPO Debut",
         publisher="(Schaeffer's Research)",
         url="/news/362321/what-history-suggest-about-spacexs-explosive-ipo-debut",
         sentiment="neutral", score=-0.1,
         summary="SpaceX IPO momentum analysis indirectly pressures Tesla as investors prefer SpaceX as the cleaner Elon Musk exposure.",
         analysis_error=None),
    dict(article_id="ab795e014e9860c7ebee0fa5", ticker="TSLA", run_date="2026-06-17", analyzed_at=TS,
         headline="Uber Robo-Taxis Move Step Closer as Self-Driving War Revs Up",
         publisher="(Barrons.com)",
         url="https://www.barrons.com/articles/uber-lucid-robo-taxis-self-driving-0779cbe8?mod=bar_FV",
         sentiment="bearish", score=-0.2,
         summary="Escalating robotaxi competition from Uber and Lucid adds headwinds to Tesla autonomous vehicle revenue plans.",
         analysis_error=None),
    dict(article_id="af0ebb1ba2d3ef2525de0eea", ticker="TSLA", run_date="2026-06-17", analyzed_at=TS,
         headline="Tesla Stock Is Down. An Argentina Charger Deal Won't Help.",
         publisher="(Barrons.com)",
         url="https://www.barrons.com/articles/tesla-stock-price-argentina-deal-11193c7f?mod=bar_FV",
         sentiment="bearish", score=-0.4,
         summary="Tesla shares are declining and a minor Argentina charging infrastructure deal is viewed as insufficient to reverse negative stock momentum.",
         analysis_error=None),
    dict(article_id="b1f321fc96f98f51b0b5bc4f", ticker="TSLA", run_date="2026-06-17", analyzed_at=TS,
         headline="TSLA Stock In Focus: Could Optimus Be The Missing Link Between Tesla And SpaceX?",
         publisher="(Stocktwits)",
         url="https://finance.yahoo.com/m/44f29475-4b34-319f-9e0d-ddff0b72f35e/tsla-stock-in-focus%3A-could.html",
         sentiment="bullish", score=0.4,
         summary="Musk comments suggesting Optimus robots could form self-replicating systems reignites bullish speculation about a Tesla-SpaceX merger unlocking long-term robotics value.",
         analysis_error=None),
    dict(article_id="b2be2609424c17a6829142ac", ticker="TSLA", run_date="2026-06-17", analyzed_at=TS,
         headline="SpaceX Shares Fall for First Time Since Blockbuster Debut",
         publisher="(Bloomberg)",
         url="https://finance.yahoo.com/markets/stocks/articles/spacex-heads-toward-fourth-day-082223913.html",
         sentiment="bearish", score=-0.3,
         summary="Retail investors net sold roughly $61M of Tesla stock since SpaceX IPO, confirming capital rotation away from TSLA toward SpaceX.",
         analysis_error=None),
    dict(article_id="b81a9bddfa65aa67ceb8b678", ticker="TSLA", run_date="2026-06-17", analyzed_at=TS,
         headline="China's Brutal Auto Price War Claims Its Biggest Victim Yet: BMW",
         publisher="(Barrons.com)",
         url="https://www.barrons.com/articles/bmw-stock-china-guidance-e935f652?mod=bar_FV",
         sentiment="bearish", score=-0.4,
         summary="China intensifying auto price war that crushed BMW guidance directly threatens Tesla profitability in its critical Chinese market.",
         analysis_error=None),
    dict(article_id="be57438e8132ac65c92fc6e4", ticker="TSLA", run_date="2026-06-17", analyzed_at=TS,
         headline="TSLA Stock Falls  Senator Raises Concerns Over Teslas Misleading FSD Safety Data",
         publisher="(Stocktwits)",
         url="https://finance.yahoo.com/m/5cb905f4-9659-362c-ac34-394af459b9fb/tsla-stock-falls-%E2%80%93-senator.html",
         sentiment="bearish", score=-0.4,
         summary="Senate pressure on Tesla FSD safety data integrity creates regulatory risk, though Goldman Sachs raising Q2 delivery estimates to 420K provides a partial offset.",
         analysis_error=None),
    dict(article_id="c564fa3f116da8b268d4e1db", ticker="TSLA", run_date="2026-06-17", analyzed_at=TS,
         headline="SpaceX to acquire Cursor in US$60 billion stock deal after blockbuster IPO",
         publisher="(DigiTimes)",
         url="https://www.digitimes.com/news/a20260617VL210/spacex-ipo-xai-startup-acquisition.html",
         sentiment="neutral", score=-0.1,
         summary="SpaceX $60B Cursor acquisition further strengthens its competing AI narrative over Tesla as Elon Musk primary technology investment.",
         analysis_error=None),
    dict(article_id="c67ca74a6fc2b37339d2568f", ticker="TSLA", run_date="2026-06-17", analyzed_at=TS,
         headline="Musk has made the impossible work. AI data centers in space won't be easy",
         publisher="(Quartz)",
         url="https://finance.yahoo.com/m/fbe58966-bdab-3276-9f87-36e46bcef3c0/musk-has-made-the-impossible.html",
         sentiment="neutral", score=0.0,
         summary="Historical analysis of Tesla and SpaceX government-backed survival provides neutral long-term context without near-term bullish or bearish catalysts.",
         analysis_error=None),
    dict(article_id="ca4ca36786c3c6fd9e259076", ticker="TSLA", run_date="2026-06-17", analyzed_at=TS,
         headline="Why SpaceX Is Buying Cursor",
         publisher="(Trefis)",
         url="https://finance.yahoo.com/m/0ceaf83c-fb10-3bc5-b731-b293c1c11d55/why-spacex-is-buying-cursor.html",
         sentiment="bearish", score=-0.2,
         summary="SpaceX expanding AI software narrative through Cursor acquisition further dilutes Tesla AI positioning with TSLA lagging the market year-to-date.",
         analysis_error=None),
    dict(article_id="da42dd9d118e424e4e29450e", ticker="TSLA", run_date="2026-06-17", analyzed_at=TS,
         headline="Uber Expands Robotaxi Ambitions With WeRide Zurich Launch, Stellantis-Wayve Global Partnership",
         publisher="(Stocktwits)",
         url="https://finance.yahoo.com/m/b8af5012-847a-3a6d-8503-fd39fe90295f/uber-expands-robotaxi.html",
         sentiment="neutral", score=-0.1,
         summary="Uber expanding global robotaxi partnerships increases the competitive field Tesla autonomous vehicle platform must navigate across multiple markets.",
         analysis_error=None),
    dict(article_id="de2c6082494cebeaa3264938", ticker="TSLA", run_date="2026-06-17", analyzed_at=TS,
         headline="SpaceX Stock Will Face a Reckoning When Investor Lockups End",
         publisher="(Barrons.com)",
         url="https://www.barrons.com/articles/spacex-stock-price-investor-lockups-37a3ea6a?mod=bar_FV",
         sentiment="neutral", score=0.0,
         summary="SpaceX lockup expiry risk article has limited direct Tesla implications though the broader SpaceX narrative continues to overshadow TSLA.",
         analysis_error=None),
    dict(article_id="de7e7cb204ec92f8a549c123", ticker="TSLA", run_date="2026-06-17", analyzed_at=TS,
         headline="Microsoft dips below 200-day moving average: Buy, hold, or sell?",
         publisher="(Yahoo Finance Video)",
         url="https://finance.yahoo.com/video/microsoft-dips-below-200-day-moving-average-buy-hold-or-sell-143813805.html",
         sentiment="bearish", score=-0.2,
         summary="Tesla inclusion among the worst-performing Mag 7 stocks in 2026 reinforces near-term bearish technical and sentiment backdrop.",
         analysis_error=None),
    dict(article_id="f2bf697f4705201507477ead", ticker="TSLA", run_date="2026-06-17", analyzed_at=TS,
         headline="Space data centers face cooling hurdles and cost barriers",
         publisher="(DigiTimes)",
         url="https://www.digitimes.com/news/a20260616PD231/spacex-space-tech-data-center-cooling-cost.html",
         sentiment="neutral", score=0.0,
         summary="Space data center technical challenges article has minimal relevance to Tesla core EV and humanoid robotics business.",
         analysis_error=None),
]

# ── AAPL ──────────────────────────────────────────────────────────────────────
aapl = [
    dict(article_id="14181efc791a14401110c4c6", ticker="AAPL", run_date="2026-06-17", analyzed_at=TS,
         headline="Apple Investors Are Tired of AI Promises, Want Tangible Progress",
         publisher="(Bloomberg)",
         url="https://finance.yahoo.com/technology/ai/articles/apple-investors-tired-ai-promises-112159204.html",
         sentiment="bearish", score=-0.5,
         summary="Investor fatigue with Apple AI delays after a disappointing WWDC has pushed AAPL to its worst week since February with no analyst revenue estimate upgrades.",
         analysis_error=None),
    dict(article_id="1ef36d41bb95ce3701d7b528", ticker="AAPL", run_date="2026-06-17", analyzed_at=TS,
         headline="Apple Looks Beyond the iPhone Upgrade Cycle",
         publisher="(GuruFocus.com)",
         url="https://finance.yahoo.com/technology/articles/apple-looks-beyond-iphone-upgrade-125955589.html",
         sentiment="bullish", score=0.3,
         summary="Apple reported 2027 roadmap for AI-camera AirPods and second-gen foldable iPhone signals meaningful hardware expansion that could revive growth beyond the iPhone upgrade cycle.",
         analysis_error=None),
    dict(article_id="22eb2ee6f67861127ae56f2f", ticker="AAPL", run_date="2026-06-17", analyzed_at=TS,
         headline="SpaceX's near $3 trillion rally comes with one big catch: Chart of the Day",
         publisher="(Yahoo Finance)",
         url="https://finance.yahoo.com/markets/article/spacexs-near-3-trillion-rally-comes-with-one-big-catch-chart-of-the-day-122114608.html",
         sentiment="neutral", score=0.1,
         summary="SpaceX valuation comparison reinforces Apple status as a high-profit mega-cap though the SpaceX narrative draws near-term investor attention away from AAPL.",
         analysis_error=None),
    dict(article_id="3cdcef9e9460efa806dfc2f1", ticker="AAPL", run_date="2026-06-17", analyzed_at=TS,
         headline="How America Got to SpaceX: The Long Trail of Big IPOs That Began in 1783",
         publisher="(Barrons.com)",
         url="https://www.barrons.com/articles/spacex-ipo-history-bank-of-north-america-sears-668fd232?mod=bar_FV",
         sentiment="neutral", score=0.0,
         summary="Historical IPO context piece has no direct implications for Apple current product and market positioning.",
         analysis_error=None),
    dict(article_id="475941cd78357b4dadf9c854", ticker="AAPL", run_date="2026-06-17", analyzed_at=TS,
         headline="Intel Stock Pops as Chip-Making Bet Moves Closer to Paying Off",
         publisher="(Barrons.com)",
         url="https://www.barrons.com/articles/intel-stock-price-today-chips-2cd104d5?mod=bar_FV",
         sentiment="bullish", score=0.3,
         summary="Intel 18A-P manufacturing milestone advances prospects of a reported Apple supply deal, potentially diversifying chip supply chain away from TSMC.",
         analysis_error=None),
    dict(article_id="7094143c225f6cf498d18499", ticker="AAPL", run_date="2026-06-17", analyzed_at=TS,
         headline="Apple Eyes AI-Powered AirPods, Foldable iPhone Launches in 2027",
         publisher="(GuruFocus.com)",
         url="https://finance.yahoo.com/technology/ai/articles/apple-eyes-ai-powered-airpods-125646364.html",
         sentiment="bullish", score=0.3,
         summary="Apple confirmed 2027 AI-camera AirPods and second-gen foldable iPhone pipeline provides potential new catalysts for hardware growth and ecosystem expansion.",
         analysis_error=None),
    dict(article_id="73f430996b7186055105110d", ticker="AAPL", run_date="2026-06-17", analyzed_at=TS,
         headline="India Bans Pavel Durov Telegram: GRAM and Crypto Hammered, Whatsapp Accused",
         publisher="(Cryptonews)",
         url="https://finance.yahoo.com/m/d5bf19f4-5e12-34dc-b116-1fff7641286d/india-bans-pavel-durov.html",
         sentiment="bearish", score=-0.2,
         summary="India temporary order forcing Apple to delist Telegram highlights App Store regulatory compliance risks in a key growth market.",
         analysis_error=None),
    dict(article_id="7ac9a24eb968ba4da7b04b6d", ticker="AAPL", run_date="2026-06-17", analyzed_at=TS,
         headline="Intel Is Fast-Tracking Its Next Upgrade. It Could Be a 'Turnaround Moment' for the Foundry.",
         publisher="(Barrons.com)",
         url="https://www.barrons.com/articles/intel-stock-price-foundry-18ap-chips-2cd104d5?mod=bar_FV",
         sentiment="bullish", score=0.2,
         summary="Intel accelerated 18A-P timeline keeps the prospect of Apple chip supply diversification alive, potentially reducing TSMC concentration risk.",
         analysis_error=None),
    dict(article_id="8898c5db2482d9c198ba00dc", ticker="AAPL", run_date="2026-06-17", analyzed_at=TS,
         headline="Looking to Ride SpaceX Stock Higher? Consider Using Options.",
         publisher="(Barrons.com)",
         url="https://www.barrons.com/articles/spacex-stock-higher-options-245a8237?mod=bar_FV",
         sentiment="neutral", score=0.0,
         summary="SpaceX options piece has no material impact on Apple market outlook.",
         analysis_error=None),
    dict(article_id="99cffb4bebbbddcf7f564496", ticker="AAPL", run_date="2026-06-17", analyzed_at=TS,
         headline="Italy opens first DMA probe into Apple over iCloud access",
         publisher="(Verdict)",
         url="https://finance.yahoo.com/m/83b0ea24-903a-31fd-832b-e5771c1e2067/italy-opens-first-dma-probe.html",
         sentiment="bearish", score=-0.4,
         summary="Italy first-ever DMA probe into Apple over iCloud interoperability adds fresh regulatory risk potentially requiring Apple to open iOS to competing cloud providers.",
         analysis_error=None),
    dict(article_id="a3a03f243a8928bcc7f8ab6c", ticker="AAPL", run_date="2026-06-17", analyzed_at=TS,
         headline="Kevin Warsh's Debutante Ball Starts at 2:00 PM",
         publisher="(Moby)",
         url="https://finance.yahoo.com/m/3dfaae2c-980a-3eb0-9ee2-4a8ff797e024/kevin-warsh%27s-debutante-ball.html",
         sentiment="neutral", score=0.1,
         summary="Intel 18A-P Apple deal rumor provides a modestly positive supply chain narrative offset by uncertain macro backdrop from the Fed meeting.",
         analysis_error=None),
    dict(article_id="cf88c786e776f6dced7ff6e0", ticker="AAPL", run_date="2026-06-17", analyzed_at=TS,
         headline="The Trump Phone Is More Novelty Than Serious Smartphone Contender",
         publisher="(Bloomberg)",
         url="https://finance.yahoo.com/technology/articles/trump-phone-more-novelty-serious-124516247.html",
         sentiment="bullish", score=0.2,
         summary="Detailed review confirming the Trump Mobile T1 phone is not a credible iPhone competitor reinforces Apple premium smartphone market dominance.",
         analysis_error=None),
    dict(article_id="d40a7c5f98bef8d559e48e75", ticker="AAPL", run_date="2026-06-17", analyzed_at=TS,
         headline="Apple's foldable iPhone launch may slip to early 2027",
         publisher="(DigiTimes)",
         url="https://www.digitimes.com/news/a20260617VL205/apple-foldable-iphone-launch-2027.html",
         sentiment="bearish", score=-0.3,
         summary="Reports of the foldable iPhone launch slipping to early 2027 continue the theme of product delays that has frustrated Apple investors this year.",
         analysis_error=None),
    dict(article_id="d943cb26a054289c93a0f9dc", ticker="AAPL", run_date="2026-06-17", analyzed_at=TS,
         headline="Tata Electronics pollution probe closure highlights lingering risks for Apple's India supply chain",
         publisher="(DigiTimes)",
         url="https://www.digitimes.com/news/a20260617VL201/apple-india-pollution-probe-iphone-production.html",
         sentiment="bearish", score=-0.2,
         summary="Tata Electronics pollution probe issues underscore ongoing supply chain vulnerabilities in Apple India manufacturing diversification strategy.",
         analysis_error=None),
    dict(article_id="ec74a6fe350a778081315b65", ticker="AAPL", run_date="2026-06-17", analyzed_at=TS,
         headline="Jabil raises annual profit forecast amid strong data center demand",
         publisher="(Reuters)",
         url="https://finance.yahoo.com/technology/articles/jabil-raises-annual-profit-forecast-121422742.html",
         sentiment="bullish", score=0.2,
         summary="Jabil raised profit forecast from Apple component manufacturing and AI-driven demand signals positive supply chain health and near-term demand visibility for Apple.",
         analysis_error=None),
]

# ── META ──────────────────────────────────────────────────────────────────────
meta = [
    dict(article_id="0ab21d988f45f0b34e2b27bd", ticker="META", run_date="2026-06-17", analyzed_at=TS,
         headline="Nvidia Stock Braced for AI Funding Squeeze",
         publisher="(Barrons.com)",
         url="https://www.barrons.com/articles/nvidia-stock-price-ai-chips-5af3e659?mod=bar_FV",
         sentiment="bearish", score=-0.2,
         summary="Questions about AI hardware spending sustainability could indirectly pressure Meta as a major Nvidia GPU customer in its AI infrastructure buildout.",
         analysis_error=None),
    dict(article_id="14181efc791a14401110c4c6", ticker="META", run_date="2026-06-17", analyzed_at=TS,
         headline="Apple Investors Are Tired of AI Promises, Want Tangible Progress",
         publisher="(Bloomberg)",
         url="https://finance.yahoo.com/technology/ai/articles/apple-investors-tired-ai-promises-112159204.html",
         sentiment="neutral", score=0.0,
         summary="Apple AI execution struggles have no material bearing on Meta ad-driven revenue model or its own AI product development trajectory.",
         analysis_error=None),
    dict(article_id="22eb2ee6f67861127ae56f2f", ticker="META", run_date="2026-06-17", analyzed_at=TS,
         headline="SpaceX's near $3 trillion rally comes with one big catch: Chart of the Day",
         publisher="(Yahoo Finance)",
         url="https://finance.yahoo.com/markets/article/spacexs-near-3-trillion-rally-comes-with-one-big-catch-chart-of-the-day-122114608.html",
         sentiment="neutral", score=0.0,
         summary="SpaceX valuation surge past Meta in market cap ranking reflects speculative enthusiasm rather than any fundamental change in Meta business.",
         analysis_error=None),
    dict(article_id="35b043cbe781c8b3162b1120", ticker="META", run_date="2026-06-17", analyzed_at=TS,
         headline="SpaceX just obliterated Facebook's 14-year options record by more than 4X  1.6 million bets in a single day",
         publisher="(Moneywise)",
         url="https://finance.yahoo.com/markets/options/articles/spacex-just-obliterated-facebooks-14-125500042.html",
         sentiment="neutral", score=-0.1,
         summary="SpaceX obliterating Meta 2012 IPO-day options record by 4x shifts market excitement and speculative capital away from Meta toward new technology stories.",
         analysis_error=None),
    dict(article_id="629e5ddf38e741b0f6d7b75d", ticker="META", run_date="2026-06-17", analyzed_at=TS,
         headline="OpenAIs Financials Leaked. Theyre Not Bad, but Theyre Not Great.",
         publisher="(Moby)",
         url="https://finance.yahoo.com/m/09d42d42-573e-3f60-a622-9695f37aa88e/openai%E2%80%99s-financials-leaked..html",
         sentiment="bearish", score=-0.2,
         summary="Leaked OpenAI financials drawing attention to Meta Reality Labs $17.7B 2024 loss as comparator heightens focus on Meta cumulative $70B+ AI spending without profitability.",
         analysis_error=None),
    dict(article_id="637a6f4bebf7f33c70ac1eb7", ticker="META", run_date="2026-06-17", analyzed_at=TS,
         headline="Wall Street ticks up ahead of first Fed policy decision under Warsh",
         publisher="(Reuters)",
         url="https://finance.yahoo.com/markets/stocks/articles/p-nasdaq-futures-inch-ahead-102857417.html",
         sentiment="bearish", score=-0.3,
         summary="Meta led communication services sector losses with a 2.2% decline as rate uncertainty and growth stock rotation weighed on richly-valued tech names.",
         analysis_error=None),
    dict(article_id="6a8921d085110aa366daf9f5", ticker="META", run_date="2026-06-17", analyzed_at=TS,
         headline="AI startup Genspark valued at $2.6 billion in latest funding round",
         publisher="(Reuters)",
         url="https://finance.yahoo.com/technology/ai/articles/genspark-ai-valued-2-6-132914723.html",
         sentiment="neutral", score=0.0,
         summary="Genspark $2.6B valuation built on ex-Meta talent highlights AI productivity opportunity but has no direct material impact on Meta core advertising and social platforms.",
         analysis_error=None),
    dict(article_id="785586a0d6827836c1af9ee8", ticker="META", run_date="2026-06-17", analyzed_at=TS,
         headline="Social Media Has a Political Problem. This Time, It's Not Going Away.",
         publisher="(Barrons.com)",
         url="https://www.barrons.com/articles/instagram-under-16-social-media-ban-7e0f8e15?mod=bar_FV",
         sentiment="bearish", score=-0.4,
         summary="UK government proposed ban on under-16s using Instagram adds to a growing regulatory wave targeting Meta social platforms and threatening its youth audience monetization.",
         analysis_error=None),
    dict(article_id="7c39383fde08297edd581009", ticker="META", run_date="2026-06-17", analyzed_at=TS,
         headline="General Atlantic in Talks to Lead Round for Chinas Kling AI",
         publisher="(Bloomberg)",
         url="https://finance.yahoo.com/technology/ai/articles/general-atlantic-talks-lead-funding-013911719.html",
         sentiment="bearish", score=-0.4,
         summary="China forced unwinding of Meta $2B Manus AI acquisition blocks a key agentic AI growth strategy and underscores geopolitical risks for Meta international AI expansion.",
         analysis_error=None),
    dict(article_id="8898c5db2482d9c198ba00dc", ticker="META", run_date="2026-06-17", analyzed_at=TS,
         headline="Looking to Ride SpaceX Stock Higher? Consider Using Options.",
         publisher="(Barrons.com)",
         url="https://www.barrons.com/articles/spacex-stock-higher-options-245a8237?mod=bar_FV",
         sentiment="neutral", score=0.0,
         summary="SpaceX options piece has no direct bearing on Meta advertising and AI business fundamentals.",
         analysis_error=None),
    dict(article_id="9fd0d27b111c3681a6dcf14f", ticker="META", run_date="2026-06-17", analyzed_at=TS,
         headline="What History Suggest About SpaceX's Explosive IPO Debut",
         publisher="(Schaeffer's Research)",
         url="/news/362321/what-history-suggest-about-spacexs-explosive-ipo-debut",
         sentiment="neutral", score=0.0,
         summary="SpaceX IPO historical analysis has negligible direct relevance to Meta core business or market outlook.",
         analysis_error=None),
    dict(article_id="a0c21ef62adfafdaef21bcd9", ticker="META", run_date="2026-06-17", analyzed_at=TS,
         headline="Meta CTO Flags Employee Morale Concerns After Recent Layoffs: Report",
         publisher="(Stocktwits)",
         url="https://finance.yahoo.com/m/98eee02e-7604-3a59-9c06-d7e3303ac4ed/meta-cto-flags-employee.html",
         sentiment="bearish", score=-0.5,
         summary="Meta CTO acknowledging morale is at a roughly 20-year low following 8000 AI-driven layoffs signals significant cultural and execution risks that could slow the AI transformation.",
         analysis_error=None),
    dict(article_id="a390556eb08f3ea17c1e1fbd", ticker="META", run_date="2026-06-17", analyzed_at=TS,
         headline="Is It Time to Sell Microsoft Stock? Why This Analyst Is Warning Investors to Exit.",
         publisher="(Barrons.com)",
         url="https://www.barrons.com/articles/microsoft-stock-sell-warning-9646e0d8?mod=bar_FV",
         sentiment="neutral", score=0.0,
         summary="Microsoft sell warning reflects broad Mag 7 investor caution but has no direct bearing on Meta specific business outlook.",
         analysis_error=None),
    dict(article_id="b03b412aa152612c798fb402", ticker="META", run_date="2026-06-17", analyzed_at=TS,
         headline="SNAP Stock Rebounds Overnight: CEO Defends Premium Specs Against META's Cheaper Glasses, But Analyst Sees A Tough Sell",
         publisher="(Stocktwits)",
         url="https://finance.yahoo.com/m/ed83c9dc-1ad4-3211-bfde-410a70353ac7/snap-stock-rebounds.html",
         sentiment="neutral", score=0.1,
         summary="Snap $2195 AR headset launch versus Meta sub-$800 smart glasses positions Meta wearables favorably on accessibility though industry-wide AR adoption remains nascent.",
         analysis_error=None),
    dict(article_id="b2be2609424c17a6829142ac", ticker="META", run_date="2026-06-17", analyzed_at=TS,
         headline="SpaceX Shares Fall for First Time Since Blockbuster Debut",
         publisher="(Bloomberg)",
         url="https://finance.yahoo.com/markets/stocks/articles/spacex-heads-toward-fourth-day-082223913.html",
         sentiment="neutral", score=-0.1,
         summary="Meta was among stocks bought alongside SpaceX during the IPO period but net retail flow data suggests some capital rotation away from established tech names.",
         analysis_error=None),
    dict(article_id="eb297cc685a7f08606ba0d5c", ticker="META", run_date="2026-06-17", analyzed_at=TS,
         headline="The Smartest Way to Play the AI Boom in 2026",
         publisher="(Oilprice.com)",
         url="https://finance.yahoo.com/technology/ai/articles/smartest-way-play-ai-boom-000000659.html",
         sentiment="neutral", score=-0.1,
         summary="Article suggesting investors look beyond standard AI plays like Meta for 2026 returns implies limited near-term upside from current META levels.",
         analysis_error=None),
]

# ── MU ────────────────────────────────────────────────────────────────────────
mu = [
    dict(article_id="139754c1091bc64bf44c5eae", ticker="MU", run_date="2026-06-17", analyzed_at=TS,
         headline="Semiconductor Stocks Climb in Premarket Trade Following Intel Manufacturing Milestone",
         publisher="(InvestorsHub)",
         url="https://finance.yahoo.com/m/9b12bced-04e4-3678-b4af-68ad2f680ebd/semiconductor-stocks-climb-in.html",
         sentiment="bullish", score=0.5,
         summary="Intel 18A-P manufacturing milestone drove Micron 3.5% higher in premarket as positive semiconductor news reinforced strong AI memory demand dynamics.",
         analysis_error=None),
    dict(article_id="22d8f5368b3f00632f778fb6", ticker="MU", run_date="2026-06-17", analyzed_at=TS,
         headline="2 Trillion-Dollar Stocks Define This Rally-SpaceX Isn't One of Them",
         publisher="(Barrons.com)",
         url="https://www.barrons.com/articles/micron-broadcom-spacex-stock-market-things-to-know-today-1e00de7a?mod=bar_FV",
         sentiment="bullish", score=0.3,
         summary="Micron highlighted as one of the trillion-dollar stocks defining the current market rally, validating its elevated market position driven by AI memory demand.",
         analysis_error=None),
    dict(article_id="22eb2ee6f67861127ae56f2f", ticker="MU", run_date="2026-06-17", analyzed_at=TS,
         headline="SpaceX's near $3 trillion rally comes with one big catch: Chart of the Day",
         publisher="(Yahoo Finance)",
         url="https://finance.yahoo.com/markets/article/spacexs-near-3-trillion-rally-comes-with-one-big-catch-chart-of-the-day-122114608.html",
         sentiment="neutral", score=0.0,
         summary="SpaceX rapid valuation surge past Micron reflects speculative enthusiasm rather than any change in Micron AI memory fundamentals.",
         analysis_error=None),
    dict(article_id="3a14a7f44b46d2ac58717a84", ticker="MU", run_date="2026-06-17", analyzed_at=TS,
         headline="Is Micron Stock's Data Center Engine Stalling, Or Just Drowned Out By AI?",
         publisher="(Trefis)",
         url="https://finance.yahoo.com/m/ff56ec7b-f008-3fc0-9435-f9166d99749b/is-micron-stock%27s-data-center.html",
         sentiment="bullish", score=0.5,
         summary="Analysis confirms Micron core data center SSD segment still grows 45% YoY while AI memory drives 257% growth, validating the complete AI transition thesis.",
         analysis_error=None),
    dict(article_id="3d7c3bc5576d67e3e65d9fc3", ticker="MU", run_date="2026-06-17", analyzed_at=TS,
         headline="Premarket movers: SpaceX, Intel, Micron Technology",
         publisher="(MarketWatch)",
         url="https://www.marketwatch.com/livecoverage/stock-market-today-s-p-500-nasdaq-dow-federal-reserve-meeting-interest-rate-decision-14-point-plan/card/premarket-movers-spacex-intel-micron-technology-W07VGpDxykVdGJ2qY2YR?mod=mw_FV",
         sentiment="bullish", score=0.3,
         summary="Micron 3% premarket gain alongside broader semiconductor strength reflects positive momentum heading into the Q3 earnings report.",
         analysis_error=None),
    dict(article_id="4a1649dbf814425e09b7cbf3", ticker="MU", run_date="2026-06-17", analyzed_at=TS,
         headline="Micron shares climb as analysts raise targets on DRAM supply squeeze",
         publisher="(Investing.com)",
         url="https://finance.yahoo.com/markets/stocks/articles/micron-shares-climb-analysts-raise-130722150.html",
         sentiment="bullish", score=0.8,
         summary="Deutsche Bank and Citi both raised Micron price targets dramatically to $1500 and $1200 respectively citing DRAM supply tightness expected to persist through 2028 with 200% ASP increases in 2026.",
         analysis_error=None),
    dict(article_id="53507b93123bd2f05fb1cae0", ticker="MU", run_date="2026-06-17", analyzed_at=TS,
         headline="Nasdaq, S&P 500 Futures Gain Ahead Of Kevin Warshs First Fed Meeting: Why SPCX, ASTS, INTC, MU, SOFI, SMCI Are In Focus",
         publisher="(Stocktwits)",
         url="https://finance.yahoo.com/m/b69ef3e1-995a-3b79-9740-c931e3b901a8/nasdaq%2C-s%26p-500-futures-gain.html",
         sentiment="bullish", score=0.3,
         summary="Micron is among the key premarket movers as chip stocks rebound ahead of the Fed decision, maintaining bullish momentum into earnings.",
         analysis_error=None),
    dict(article_id="54a4319ae60deb7e6d3135be", ticker="MU", run_date="2026-06-17", analyzed_at=TS,
         headline="AMD, Marvell, and More Stocks That Explain Today's Market",
         publisher="(Barrons.com)",
         url="https://www.barrons.com/articles/stock-movers-d7fc8668?mod=bar_FV",
         sentiment="bullish", score=0.3,
         summary="Micron inclusion in the day's AI and tech comeback movers reflects broad semiconductor sector strength in the AI infrastructure buildout theme.",
         analysis_error=None),
    dict(article_id="56852855340bc56b908cefb4", ticker="MU", run_date="2026-06-17", analyzed_at=TS,
         headline="MU, AMAT Stocks Rise Premarket: Analysts Justify Bull Case For Memory Darlings Amid Supply Crunch",
         publisher="(Stocktwits)",
         url="https://finance.yahoo.com/m/7046b7d5-4428-3328-ae47-5a1bf09610fb/mu%2C-amat-stocks-rise.html",
         sentiment="bullish", score=0.7,
         summary="Multiple Wall Street analysts reinforcing the bull case for Micron ahead of Q3 earnings with elevated gross margin expectations and Q3 EPS consensus of $19.72 on $34.5B revenue.",
         analysis_error=None),
    dict(article_id="637a6f4bebf7f33c70ac1eb7", ticker="MU", run_date="2026-06-17", analyzed_at=TS,
         headline="S&P, Nasdaq set to rise ahead of first Fed policy decision under Warsh",
         publisher="(Reuters)",
         url="https://finance.yahoo.com/markets/stocks/articles/p-nasdaq-futures-inch-ahead-102857417.html",
         sentiment="bullish", score=0.4,
         summary="Chipmakers including Micron rose 2.5 to 4% as the semiconductor sector staged a broad rebound ahead of the Fed meeting, reversing Tuesday weakness.",
         analysis_error=None),
    dict(article_id="67550a617c4c46fe77bc4f95", ticker="MU", run_date="2026-06-17", analyzed_at=TS,
         headline="Stocks to Watch: SpaceX, Intel, BMW",
         publisher="(The Wall Street Journal)",
         url="https://www.wsj.com/livecoverage/fed-meeting-warsh-interest-rate-06-17-2026/card/stocks-to-watch-spacex-intel-bmw-9vI84PMRRZJT5l3QRxE2?mod=wsj_FV",
         sentiment="bullish", score=0.3,
         summary="Micron recovering ground lost in prior session second-worst semiconductor day of 2026 suggests the dip was an overreaction to broader market weakness.",
         analysis_error=None),
    dict(article_id="7bf948f844f3f078c4328aa2", ticker="MU", run_date="2026-06-17", analyzed_at=TS,
         headline="WDC Stock To $1,000? Retail Traders Pile Into Memory Underdog After SNDK, MU Rallies: Here's A Key Signal Left Unnoticed",
         publisher="(Stocktwits)",
         url="https://finance.yahoo.com/m/aab205e5-6fb9-3c8c-b0a3-3db4c1f535d5/wdc-stock-to-%241%2C000%3F-retail.html",
         sentiment="bearish", score=-0.2,
         summary="Retail traders rotating from Micron into Western Digital with Stocktwits sentiment on MU turning bearish may signal near-term momentum headwind as the memory supercycle broadens.",
         analysis_error=None),
    dict(article_id="86342a24de952a8a3e3aa5dd", ticker="MU", run_date="2026-06-17", analyzed_at=TS,
         headline="Chip stocks rebound premarket as Intel manufacturing update lifts sector",
         publisher="(Investing.com)",
         url="https://finance.yahoo.com/technology/articles/chip-stocks-rebound-premarket-intel-112701439.html",
         sentiment="bullish", score=0.4,
         summary="Micron 3.5% premarket rebound as Intel manufacturing milestone lifts semiconductors signals positive near-term price momentum ahead of earnings.",
         analysis_error=None),
    dict(article_id="af1dd1659c6b42b2b191c3fa", ticker="MU", run_date="2026-06-17", analyzed_at=TS,
         headline="Micron Stock Is Rising Again Because That's Just What It Does",
         publisher="(Barrons.com)",
         url="https://www.barrons.com/articles/micron-stock-price-today-memory-chips-81a621ee?mod=bar_FV",
         sentiment="bullish", score=0.4,
         summary="Barron's characterizing Micron advance as simply resuming its relentless rally reflects strong market confidence in the AI-driven memory chip supercycle thesis.",
         analysis_error=None),
    dict(article_id="b1a45a0de5cd4a6b1fbb5a1e", ticker="MU", run_date="2026-06-17", analyzed_at=TS,
         headline="Why Did MU, WDC, LION Stocks Surge To 52-Week Highs Today?",
         publisher="(Stocktwits)",
         url="https://finance.yahoo.com/m/fe6582d0-e8fb-3bc5-8582-a35fd6bbd63d/why-did-mu%2C-wdc%2C-lion-stocks.html",
         sentiment="bullish", score=0.5,
         summary="TD Cowen dramatic price target hike to $1500 from $660 confirms the AI memory demand thesis even as MU pulled back 6% from its 52-week high on profit-taking.",
         analysis_error=None),
    dict(article_id="fc28996d4843e79dcc9b046e", ticker="MU", run_date="2026-06-17", analyzed_at=TS,
         headline="Micron Stock Is Gaining Again Because That's Just What It Does",
         publisher="(Barrons.com)",
         url="https://www.barrons.com/articles/micron-stock-price-analyst-target-1500-earnings-81a621ee?mod=bar_FV",
         sentiment="bullish", score=0.4,
         summary="Micron continued market advance affirms the strong fundamental tailwind from AI-driven DRAM demand and the tightening memory supply-demand imbalance into 2028.",
         analysis_error=None),
]

# ── ENPH ──────────────────────────────────────────────────────────────────────
enph = [
    dict(article_id="a807f27f272b1a1408f49390", ticker="ENPH", run_date="2026-06-17", analyzed_at=TS,
         headline="Enphase Energy to Showcase Product Innovations at Intersolar Europe",
         publisher="(GlobeNewswire)",
         url="/news/362298/enphase-energy-to-showcase-product-innovations-at-intersolar-europe",
         sentiment="bullish", score=0.3,
         summary="Enphase showcase at Intersolar Europe signals continued product innovation and engagement with the European solar market, a key growth region for the company.",
         analysis_error=None),
    dict(article_id="d6daa1db2ce21cf6b3e53a10", ticker="ENPH", run_date="2026-06-17", analyzed_at=TS,
         headline="Lyft upgraded, Leidos downgraded: Wall Street's top analyst calls",
         publisher="(The Fly)",
         url="https://finance.yahoo.com/markets/stocks/articles/lyft-upgraded-leidos-downgraded-wall-134756673.html",
         sentiment="neutral", score=0.0,
         summary="Wall Street analyst calls roundup has no direct mention of Enphase, providing no new market signal for the stock.",
         analysis_error=None),
]

# ── HOOD ──────────────────────────────────────────────────────────────────────
hood = [
    dict(article_id="2ecd1f804d284b80a4af1639", ticker="HOOD", run_date="2026-06-17", analyzed_at=TS,
         headline="Why Is The Crypto Market Up Today?",
         publisher="(BeInCrypto)",
         url="https://finance.yahoo.com/m/a073a26d-d1e4-3ccc-a0ae-5ba418ba6862/why-is-the-crypto-market-up.html",
         sentiment="neutral", score=0.0,
         summary="Crypto market minor gains and HOOD 10% layoff announcement create mixed signals for Robinhood with trading volumes record but organizational disruption ongoing.",
         analysis_error=None),
    dict(article_id="54b4a22e2318552cb0ce7626", ticker="HOOD", run_date="2026-06-17", analyzed_at=TS,
         headline="Will Kevin Warsh Trigger a Bitcoin Selloff Today?",
         publisher="(Trefis)",
         url="https://finance.yahoo.com/m/26ce22fc-2fb5-3faa-9f49-57b2d015e5df/will-kevin-warsh-trigger-a.html",
         sentiment="bearish", score=-0.3,
         summary="Historical pattern of Bitcoin declining in the 48 hours after FOMC decisions poses a near-term risk to Robinhood crypto trading volumes if the pattern repeats under Warsh.",
         analysis_error=None),
    dict(article_id="701c3a9b2dd200e7b30c6cb0", ticker="HOOD", run_date="2026-06-17", analyzed_at=TS,
         headline="Robinhood Reduces Workforce 10% While Pledging to Keep Hiring",
         publisher="(BeInCrypto)",
         url="https://finance.yahoo.com/m/1b379a0f-69c2-3424-bde5-fb375cb501b9/robinhood-reduces-workforce.html",
         sentiment="bullish", score=0.4,
         summary="Robinhood 10% workforce reduction framed as a proactive efficiency move from strength with record June trading volumes across equities, options, and prediction markets supporting the bullish thesis.",
         analysis_error=None),
    dict(article_id="a8542390ac98e67bfd44e24f", ticker="HOOD", run_date="2026-06-17", analyzed_at=TS,
         headline="Trading app Robinhood to shed 10% of staff",
         publisher="(Private Banker International)",
         url="https://finance.yahoo.com/m/ac7e98b4-e047-3c94-8350-b804616666c0/trading-app-robinhood-to-shed.html",
         sentiment="bullish", score=0.3,
         summary="Robinhood proactive headcount reduction amid record trading activity signals disciplined cost management and strong business momentum heading into Q2.",
         analysis_error=None),
    dict(article_id="a948da78641085075a70abb0", ticker="HOOD", run_date="2026-06-17", analyzed_at=TS,
         headline="HOOD Stock Gets A New $105 Price Target  Here's What Bulls Think The Market Is Missing",
         publisher="(Stocktwits)",
         url="https://finance.yahoo.com/m/7b4c4e7f-e947-33d4-9546-57551621cae3/hood-stock-gets-a-new-%24105.html",
         sentiment="bullish", score=0.6,
         summary="Deutsche Bank and Argus Research both raised Robinhood price targets to $105 and $110 respectively citing record June trading volumes and multi-year high-growth potential with the stock rising over 4%.",
         analysis_error=None),
    dict(article_id="fcda904fb52867852134d2d8", ticker="HOOD", run_date="2026-06-17", analyzed_at=TS,
         headline="Coinbase Joins Tokenized Stock Race With Onchain Shares and Dividends",
         publisher="(CryptoProwl)",
         url="https://finance.yahoo.com/m/c58f2bbc-22d0-3372-9825-613a06ebf385/coinbase-joins-tokenized.html",
         sentiment="neutral", score=-0.1,
         summary="Coinbase entering the tokenized equities market alongside Robinhood planned Europe rollout signals growing competition in this emerging product category.",
         analysis_error=None),
]

# ── ORCL ──────────────────────────────────────────────────────────────────────
orcl = [
    dict(article_id="1ffd7afb12c3e47fdb0272ff", ticker="ORCL", run_date="2026-06-17", analyzed_at=TS,
         headline="MSFT Falls 2% On Tuesday  Microsoft Reportedly Walks Away From $3B Oracle Cloud Deal",
         publisher="(Stocktwits)",
         url="https://finance.yahoo.com/m/c1e6475b-35b5-36d9-b48a-5a3d90ef8d13/msft-falls-2%25-on-tuesday-%E2%80%94.html",
         sentiment="bearish", score=-0.5,
         summary="Microsoft abandonment of a $3B Oracle cloud deal due to FedRAMP certification failure exposes Oracle infrastructure limitations in serving government-adjacent enterprise workloads.",
         analysis_error=None),
    dict(article_id="546263b0354f0d9f2844e3fb", ticker="ORCL", run_date="2026-06-17", analyzed_at=TS,
         headline="Microsoft Walks Away From Potential $3 Billion Oracle Deal, Stock Dips",
         publisher="(GuruFocus.com)",
         url="https://finance.yahoo.com/markets/stocks/articles/microsoft-walks-away-potential-3-145756223.html",
         sentiment="bearish", score=-0.4,
         summary="Microsoft walking away from a $3B+ Oracle data center lease over security compliance gaps creates near-term revenue headwinds and raises questions about Oracle government cloud certification readiness.",
         analysis_error=None),
    dict(article_id="629e5ddf38e741b0f6d7b75d", ticker="ORCL", run_date="2026-06-17", analyzed_at=TS,
         headline="OpenAIs Financials Leaked. Theyre Not Bad, but Theyre Not Great.",
         publisher="(Moby)",
         url="https://finance.yahoo.com/m/09d42d42-573e-3f60-a622-9695f37aa88e/openai%E2%80%99s-financials-leaked..html",
         sentiment="bearish", score=-0.3,
         summary="Leaked OpenAI financials showing a $38.5B net loss create uncertainty around Oracle strategic bet on OpenAI as a key AI infrastructure customer backed by Larry Ellison.",
         analysis_error=None),
    dict(article_id="c1ab454df9a0e3585fb6802a", ticker="ORCL", run_date="2026-06-17", analyzed_at=TS,
         headline="Lightpath Monetizes Digital Services and Powers AI-Driven Innovation with Oracle",
         publisher="(PR Newswire)",
         url="/news/362291/lightpath-monetizes-digital-services-and-powers-ai-driven-innovation-with-oracle",
         sentiment="bullish", score=0.2,
         summary="Lightpath Oracle partnership for AI-driven digital services represents a positive customer adoption signal for Oracle cloud and AI infrastructure platform.",
         analysis_error=None),
]

# ── GOOG ──────────────────────────────────────────────────────────────────────
goog = [
    dict(article_id="021a6545b5a4b8c275061175", ticker="GOOG", run_date="2026-06-17", analyzed_at=TS,
         headline="Startup Backed by Ex-Google CEO Debuts Robot, LG Partnership",
         publisher="(Bloomberg)",
         url="https://finance.yahoo.com/technology/ai/articles/startup-backed-ex-google-ceo-030704320.html",
         sentiment="neutral", score=0.0,
         summary="Ex-Google CEO Eric Schmidt new Genesis AI robotics startup has no direct negative impact on Alphabet but signals competitive activity in AI by former leadership.",
         analysis_error=None),
    dict(article_id="140832b3004f26a3e9dad280", ticker="GOOG", run_date="2026-06-17", analyzed_at=TS,
         headline="Big Tech-backed coalition for carbon removal increases funding by $915 million, adds Anthropic",
         publisher="(Reuters)",
         url="https://finance.yahoo.com/technology/ai/articles/big-tech-backed-coalition-carbon-120338720.html",
         sentiment="bullish", score=0.2,
         summary="Google-backed Frontier coalition $915M expansion in carbon removal signals Alphabet continued leadership in sustainable technology investments and ESG positioning.",
         analysis_error=None),
    dict(article_id="14181efc791a14401110c4c6", ticker="GOOG", run_date="2026-06-17", analyzed_at=TS,
         headline="Apple Investors Are Tired of AI Promises, Want Tangible Progress",
         publisher="(Bloomberg)",
         url="https://finance.yahoo.com/technology/ai/articles/apple-investors-tired-ai-promises-112159204.html",
         sentiment="neutral", score=0.0,
         summary="Apple AI struggles have no direct bearing on Alphabet competitive positioning in AI products and services.",
         analysis_error=None),
    dict(article_id="19540cb5e083c4608ba3feef", ticker="GOOG", run_date="2026-06-17", analyzed_at=TS,
         headline="Amazon Faces New Ad Pricing Scrutiny",
         publisher="(GuruFocus.com)",
         url="https://finance.yahoo.com/media-advertising/articles/amazon-faces-ad-pricing-scrutiny-124642635.html",
         sentiment="bearish", score=-0.3,
         summary="FTC reported investigation into whether Google misled advertisers on ad terms and pricing creates regulatory risk for Alphabet dominant advertising business.",
         analysis_error=None),
    dict(article_id="22eb2ee6f67861127ae56f2f", ticker="GOOG", run_date="2026-06-17", analyzed_at=TS,
         headline="SpaceX's near $3 trillion rally comes with one big catch: Chart of the Day",
         publisher="(Yahoo Finance)",
         url="https://finance.yahoo.com/markets/article/spacexs-near-3-trillion-rally-comes-with-one-big-catch-chart-of-the-day-122114608.html",
         sentiment="neutral", score=0.1,
         summary="SpaceX valuation comparison reinforces Alphabet status as a proven-profit tech titan providing a favorable contrast to loss-making new entrants.",
         analysis_error=None),
    dict(article_id="4d00c4a6cb515f7eaac0d21a", ticker="GOOG", run_date="2026-06-17", analyzed_at=TS,
         headline="Uber and Lucid pick Houston as next robotaxi market as battle with Waymo, Tesla heats up",
         publisher="(Yahoo Finance)",
         url="https://finance.yahoo.com/markets/stocks/article/uber-and-lucid-pick-houston-as-next-robotaxi-market-as-battle-with-waymo-tesla-heats-up-111946695.html",
         sentiment="bullish", score=0.3,
         summary="Uber-Lucid robotaxi expansion into Houston confirms the intensifying commercial market that Alphabet Waymo already operates in, validating Waymo first-mover advantage.",
         analysis_error=None),
    dict(article_id="59bcb6e347edc51c4762e01c", ticker="GOOG", run_date="2026-06-17", analyzed_at=TS,
         headline="HSBC partners with Google Cloud to expand AI usage",
         publisher="(Reuters)",
         url="https://finance.yahoo.com/technology/ai/articles/hsbc-partners-google-cloud-expand-230425539.html",
         sentiment="bullish", score=0.5,
         summary="HSBC multi-year Google Cloud partnership targeting 200+ AI tasks and $100M+ revenue/efficiency improvements per project demonstrates strong enterprise adoption of Google cloud AI capabilities.",
         analysis_error=None),
    dict(article_id="637a6f4bebf7f33c70ac1eb7", ticker="GOOG", run_date="2026-06-17", analyzed_at=TS,
         headline="Wall Street ticks up ahead of first Fed policy decision under Warsh",
         publisher="(Reuters)",
         url="https://finance.yahoo.com/markets/stocks/articles/p-nasdaq-futures-inch-ahead-102857417.html",
         sentiment="bearish", score=-0.3,
         summary="Alphabet 1.6% decline as communication services led tech losses reflects investor nervousness about rate outlook and growth stock valuations.",
         analysis_error=None),
    dict(article_id="73f430996b7186055105110d", ticker="GOOG", run_date="2026-06-17", analyzed_at=TS,
         headline="India Bans Pavel Durov Telegram: GRAM and Crypto Hammered, Whatsapp Accused",
         publisher="(Cryptonews)",
         url="https://finance.yahoo.com/m/d5bf19f4-5e12-34dc-b116-1fff7641286d/india-bans-pavel-durov.html",
         sentiment="bearish", score=-0.1,
         summary="India temporary order requiring Google to delist Telegram from the Play Store creates minor App Store regulatory compliance risk in a key growth market.",
         analysis_error=None),
    dict(article_id="837778fd420cacf2de80cc78", ticker="GOOG", run_date="2026-06-17", analyzed_at=TS,
         headline="UK orders Google to improve search transparency to boost competition",
         publisher="(Reuters)",
         url="https://finance.yahoo.com/technology/articles/uk-regulator-sets-conduct-requirements-090941953.html",
         sentiment="bearish", score=-0.3,
         summary="UK Competition and Markets Authority imposing new transparency and fair-ranking obligations on Google search creates compliance costs and potential threats to Google search monetization.",
         analysis_error=None),
    dict(article_id="9f9fbb190fdee135862f836e", ticker="GOOG", run_date="2026-06-17", analyzed_at=TS,
         headline="Uber will bring its premium robotaxi service to Houston in 2027",
         publisher="(TechCrunch)",
         url="https://finance.yahoo.com/technology/articles/uber-bring-premium-robotaxi-houston-110000098.html",
         sentiment="bullish", score=0.3,
         summary="Waymo head-to-head robotaxi competition with Uber in both San Francisco and Houston validates Alphabet years of autonomous vehicle investment and strengthens Waymo commercial prospects.",
         analysis_error=None),
    dict(article_id="9fa1ee00f3d35165f34ce4e1", ticker="GOOG", run_date="2026-06-17", analyzed_at=TS,
         headline="Startups building orbital data centers before Big Tech",
         publisher="(Quartz)",
         url="https://finance.yahoo.com/m/d7531a88-40de-3b68-bc77-c7c9717a2c2e/startups-building-orbital.html",
         sentiment="bullish", score=0.2,
         summary="Google reported 2027 prototype satellite timeline in the orbital data center race positions Alphabet ahead of most Big Tech competitors in this emerging market.",
         analysis_error=None),
    dict(article_id="a05f6960238592c72eb04e06", ticker="GOOG", run_date="2026-06-17", analyzed_at=TS,
         headline="UK orders Google to improve search transparency to aid competition",
         publisher="(Reuters Videos)",
         url="https://finance.yahoo.com/video/uk-orders-google-improve-search-135906656.html",
         sentiment="bearish", score=-0.2,
         summary="UK regulatory orders on Google search transparency add compliance burden and risk to Alphabet dominant market position in search.",
         analysis_error=None),
    dict(article_id="b2be2609424c17a6829142ac", ticker="GOOG", run_date="2026-06-17", analyzed_at=TS,
         headline="SpaceX Shares Fall for First Time Since Blockbuster Debut",
         publisher="(Bloomberg)",
         url="https://finance.yahoo.com/markets/stocks/articles/spacex-heads-toward-fourth-day-082223913.html",
         sentiment="neutral", score=0.0,
         summary="SpaceX IPO activity data showing Alphabet among combined buy targets provides minimal signal for Google fundamental outlook.",
         analysis_error=None),
    dict(article_id="b5b6f85f2c986faf787a9038", ticker="GOOG", run_date="2026-06-17", analyzed_at=TS,
         headline="Google Rolls Out Android 17, More Gemini Features Arrive This Summer",
         publisher="(GuruFocus.com)",
         url="https://finance.yahoo.com/m/84bfce8c-0909-3a1c-b534-37353bbad9f6/google-rolls-out-android-17%2C.html",
         sentiment="bullish", score=0.4,
         summary="Android 17 rollout with enhanced features and upcoming Gemini Intelligence integration reinforces Google strong mobile AI platform positioning heading into summer.",
         analysis_error=None),
    dict(article_id="f6fbcc45c223c02512dd4628", ticker="GOOG", run_date="2026-06-17", analyzed_at=TS,
         headline="Alphabet Begins Android 17 Rollout",
         publisher="(GuruFocus.com)",
         url="https://finance.yahoo.com/m/aa060483-68db-31de-8ac8-b99972c660e0/alphabet-begins-android-17.html",
         sentiment="bullish", score=0.3,
         summary="Android 17 launch with multitasking improvements and upcoming Gemini AI features keeps Alphabet competitive in the AI-integrated mobile ecosystem.",
         analysis_error=None),
    dict(article_id="fa4677e58641b9f525d56721", ticker="GOOG", run_date="2026-06-17", analyzed_at=TS,
         headline="AI use in UK hits 'tipping point' as companies scale up, Google exec says",
         publisher="(Reuters)",
         url="https://finance.yahoo.com/technology/ai/articles/ai-uk-hits-tipping-point-111442805.html",
         sentiment="bullish", score=0.4,
         summary="Google Cloud VP highlighting UK AI adoption reaching a tipping point with companies scaling deployments signals accelerating enterprise cloud AI revenue for Alphabet.",
         analysis_error=None),
]

# ── MSFT ──────────────────────────────────────────────────────────────────────
msft = [
    dict(article_id="118b818164e110da8e45f740", ticker="MSFT", run_date="2026-06-17", analyzed_at=TS,
         headline="Microsoft Weighs DeepSeek Models for Lower-Cost Copilot",
         publisher="(GuruFocus.com)",
         url="https://finance.yahoo.com/technology/ai/articles/microsoft-weighs-deepseek-models-lower-124905817.html",
         sentiment="neutral", score=-0.1,
         summary="Microsoft exploring cheaper DeepSeek models for Copilot signals cost management discipline but may raise concerns about competitive differentiation vs OpenAI-powered tools.",
         analysis_error=None),
    dict(article_id="1ffd7afb12c3e47fdb0272ff", ticker="MSFT", run_date="2026-06-17", analyzed_at=TS,
         headline="MSFT Falls 2% On Tuesday  Microsoft Reportedly Walks Away From $3B Oracle Cloud Deal",
         publisher="(Stocktwits)",
         url="https://finance.yahoo.com/m/c1e6475b-35b5-36d9-b48a-5a3d90ef8d13/msft-falls-2%25-on-tuesday-%E2%80%94.html",
         sentiment="bearish", score=-0.4,
         summary="Microsoft stock fell 2% after abandoning $3B Oracle cloud deal talks, highlighting infrastructure capacity constraints that could slow Azure growth.",
         analysis_error=None),
    dict(article_id="22eb2ee6f67861127ae56f2f", ticker="MSFT", run_date="2026-06-17", analyzed_at=TS,
         headline="SpaceX's near $3 trillion rally comes with one big catch: Chart of the Day",
         publisher="(Yahoo Finance)",
         url="https://finance.yahoo.com/markets/article/spacexs-near-3-trillion-rally-comes-with-one-big-catch-chart-of-the-day-122114608.html",
         sentiment="bearish", score=-0.3,
         summary="SpaceX briefly surpassing Microsoft in market cap underscores the market perception that MSFT $190B capex plan has yet to translate into sufficient earnings growth premium.",
         analysis_error=None),
    dict(article_id="3009f9a3aa3ed96ae436b84f", ticker="MSFT", run_date="2026-06-17", analyzed_at=TS,
         headline="Nasdaq and S&P 500 slip while Dow hits record high",
         publisher="(Reuters Videos)",
         url="https://finance.yahoo.com/video/nasdaq-p-500-slip-while-225342405.html",
         sentiment="neutral", score=-0.1,
         summary="Nasdaq weakness while the Dow hits records reflects continued pressure on growth-oriented Microsoft shares.",
         analysis_error=None),
    dict(article_id="367968862b066362ff039d71", ticker="MSFT", run_date="2026-06-17", analyzed_at=TS,
         headline="AI era reshapes power dynamics between software firms and model providers",
         publisher="(DigiTimes)",
         url="https://www.digitimes.com/news/a20260616PD210/software-technology-ceo-anthropic.html",
         sentiment="neutral", score=-0.1,
         summary="Shifting power dynamics between AI model providers and software companies create strategic uncertainty for Microsoft position in the AI software stack.",
         analysis_error=None),
    dict(article_id="5b1b0412279418bd77bdfb6b", ticker="MSFT", run_date="2026-06-17", analyzed_at=TS,
         headline="SpaceX stock passes Amazon in market cap after record IPO",
         publisher="(Quartz)",
         url="https://finance.yahoo.com/m/c0d9b577-8be0-3a2e-986f-1c584ec799de/spacex-stock-passes-amazon-in.html",
         sentiment="bearish", score=-0.4,
         summary="Microsoft stock down 19% year-to-date and trading below 200-day moving average with SpaceX rapid valuation approach highlighting the stark contrast between MSFT fundamentals and investor sentiment.",
         analysis_error=None),
    dict(article_id="6a8921d085110aa366daf9f5", ticker="MSFT", run_date="2026-06-17", analyzed_at=TS,
         headline="AI startup Genspark valued at $2.6 billion in latest funding round",
         publisher="(Reuters)",
         url="https://finance.yahoo.com/technology/ai/articles/genspark-ai-valued-2-6-132914723.html",
         sentiment="neutral", score=0.1,
         summary="Genspark $2.6B funding with Microsoft as a key partner indicates continued strong ecosystem demand for Microsoft AI and cloud platform.",
         analysis_error=None),
    dict(article_id="785586a0d6827836c1af9ee8", ticker="MSFT", run_date="2026-06-17", analyzed_at=TS,
         headline="Social Media Has a Political Problem. This Time, It's Not Going Away.",
         publisher="(Barrons.com)",
         url="https://www.barrons.com/articles/instagram-under-16-social-media-ban-7e0f8e15?mod=bar_FV",
         sentiment="neutral", score=0.0,
         summary="Social media under-16 ban proposals in the UK have minimal direct bearing on Microsoft enterprise-focused business.",
         analysis_error=None),
    dict(article_id="8a783fa4351f62471e921e19", ticker="MSFT", run_date="2026-06-17", analyzed_at=TS,
         headline="SpaceX's hot debut sheds more light on Microsoft's dreadful stock price",
         publisher="(Yahoo Finance)",
         url="https://finance.yahoo.com/markets/stocks/article/spacexs-hot-debut-sheds-more-light-on-microsofts-dreadful-stock-price-112348867.html",
         sentiment="bearish", score=-0.6,
         summary="Microsoft 2026 stock underperformance of negative 19% YTD below its 200-day moving average reflects investor discomfort with $190B capex and competitive pressure from AI tools like Anthropic Claude Cowork.",
         analysis_error=None),
    dict(article_id="8fb176a12987afc3a827f7ae", ticker="MSFT", run_date="2026-06-17", analyzed_at=TS,
         headline="SpaceX Adds to Historic Rally as Market Value Moves Beyond Amazon",
         publisher="(InvestorsHub)",
         url="https://finance.yahoo.com/m/513925f2-78ab-3701-b13d-1c6ac6ce91bd/spacex-adds-to-historic-rally.html",
         sentiment="bearish", score=-0.2,
         summary="SpaceX brief valuation surge above Microsoft further reinforces the negative narrative around MSFT stalled stock performance in 2026.",
         analysis_error=None),
    dict(article_id="9273b7b0c7485fe2a05c306c", ticker="MSFT", run_date="2026-06-17", analyzed_at=TS,
         headline="Analysts' Top S&P 500 Stocks to Buy Now",
         publisher="(Kiplinger)",
         url="https://finance.yahoo.com/m/e9c76bf1-e609-37c2-a180-ded6380a141c/analysts%27-top-s%26p-500-stocks.html",
         sentiment="neutral", score=0.0,
         summary="Mag 7 stocks including Microsoft cited as being in pronounced drawdowns with potential rotation value, though MSFT is not specifically highlighted as a top buy.",
         analysis_error=None),
    dict(article_id="a390556eb08f3ea17c1e1fbd", ticker="MSFT", run_date="2026-06-17", analyzed_at=TS,
         headline="Is It Time to Sell Microsoft Stock? Why This Analyst Is Warning Investors to Exit.",
         publisher="(Barrons.com)",
         url="https://www.barrons.com/articles/microsoft-stock-sell-warning-9646e0d8?mod=bar_FV",
         sentiment="bearish", score=-0.5,
         summary="Analyst warning investors to exit Microsoft despite its lagging performance reflects conviction that downside risks from capex overhang and AI competition are not yet fully priced in.",
         analysis_error=None),
    dict(article_id="b2be2609424c17a6829142ac", ticker="MSFT", run_date="2026-06-17", analyzed_at=TS,
         headline="SpaceX Shares Fall for First Time Since Blockbuster Debut",
         publisher="(Bloomberg)",
         url="https://finance.yahoo.com/markets/stocks/articles/spacex-heads-toward-fourth-day-082223913.html",
         sentiment="neutral", score=-0.1,
         summary="SpaceX pullback context article showing retail investor rotation patterns provides limited direct signal for Microsoft outlook.",
         analysis_error=None),
    dict(article_id="de7e7cb204ec92f8a549c123", ticker="MSFT", run_date="2026-06-17", analyzed_at=TS,
         headline="Microsoft dips below 200-day moving average: Buy, hold, or sell?",
         publisher="(Yahoo Finance Video)",
         url="https://finance.yahoo.com/video/microsoft-dips-below-200-day-moving-average-buy-hold-or-sell-143813805.html",
         sentiment="bearish", score=-0.4,
         summary="Multiple strategists are underweight Microsoft with the stock breaking below its 200-day moving average back to 2025/2026 lows with no clear near-term catalyst to reverse the trend.",
         analysis_error=None),
    dict(article_id="eb297cc685a7f08606ba0d5c", ticker="MSFT", run_date="2026-06-17", analyzed_at=TS,
         headline="The Smartest Way to Play the AI Boom in 2026",
         publisher="(Oilprice.com)",
         url="https://finance.yahoo.com/technology/ai/articles/smartest-way-play-ai-boom-000000659.html",
         sentiment="neutral", score=-0.1,
         summary="Suggestion that the cloud trade including Microsoft is already fully priced implies limited near-term upside for MSFT beyond current expectations.",
         analysis_error=None),
    dict(article_id="ffbd36b6ae158d6d5827c1e7", ticker="MSFT", run_date="2026-06-17", analyzed_at=TS,
         headline="SpaceX's IPO Reshapes Space Trade  Here's Why Shorts Are Piling Into ASTS And SPCE",
         publisher="(Stocktwits)",
         url="https://finance.yahoo.com/m/ca093834-b48e-38f9-834c-bb3e9dd55fad/spacex%27s-ipo-reshapes-space.html",
         sentiment="bearish", score=-0.2,
         summary="SpaceX record IPO reshaping space sector capital flows reinforces the narrative of investment attention shifting away from traditional mega-caps like Microsoft.",
         analysis_error=None),
]

# Run all
append_records("TSLA", tsla)
append_records("AAPL", aapl)
append_records("META", meta)
append_records("MU", mu)
append_records("ENPH", enph)
append_records("HOOD", hood)
append_records("ORCL", orcl)
append_records("GOOG", goog)
append_records("MSFT", msft)

total = sum(len(x) for x in [tsla, aapl, meta, mu, enph, hood, orcl, goog, msft])
print(f"BATCH COMPLETE: 9 tickers, {total} total records")
